name: Publish Docker image  

on:   
  push:
    branches:  
      - 'master'
    tags:       
      - '*'  
jobs: 

  push_to_registry:  
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm repository
        uses: actions/checkout@v2
        with:
          repository: ShawnYang-95/helm-charts
          ref: master
          path: todo

      - name: Update image version in value.yaml
        run: |
          cd todo
          sed -i '/frontend:/,/service:/s/\(tag:\s*\).*/\1latestes/' values.yaml
          git add values.yaml
          git commit -m "Update image version to latest"
          git push https://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@github.com/ShawnYang-95/helm-charts.git master
